export const TEST_LOADED='TEST_LOADED';

export const TOPTEN_LOADING='TOPTEN_LOADING';
export const TOPTEN_LOADED='TOPTEN_LOADED';

export const POST_LOADING='POST_LOADING';
export const POST_LOADED='POST_LOADED';