export const TOPTEN_LOADING='TOPTEN_LOADING';
export const TOPTEN_LOADED='TOPTEN_LOADED';

export const POST_LOADING='POST_LOADING';
export const POST_LOADED='POST_LOADED';
export const POST_MORE_LOADING='POST_MORE_LOADING';
export const POST_MORE_LOADED='POST_MORE_LOADED';

export const BOARD_LOADING='BOARD_LOADING';
export const BOARD_LOADED='BOARD_LOADED';
export const BOARD_MORE_LOADING='BOARD_MORE_LOADING';
export const BOARD_MORE_LOADED='BOARD_MORE_LOADED';

export const HOTSPOT_LOADING='HOTSPOT_LOADING';
export const HOTSPOT_LOADED='HOTSPOT_LOADED';

export const PERSONAL_DEFAULT_USER_LOADING='PERSONAL_DEFAULT_USER_LOADING';
export const PERSONAL_DEFAULT_USER_LOADED='PERSONAL_DEFAULT_USER_LOADED';
