let emoji=new Map();
emoji.set(0,require('../../resources/emoji/0.gif'));
emoji.set(2,require('../../resources/emoji/2.gif'));
emoji.set(3,require('../../resources/emoji/3.gif'));
emoji.set(4,require('../../resources/emoji/4.gif'));
emoji.set(6,require('../../resources/emoji/6.gif'));
emoji.set(7,require('../../resources/emoji/7.gif'));
emoji.set(9,require('../../resources/emoji/9.gif'));
emoji.set(10,require('../../resources/emoji/10.gif'));
emoji.set(11,require('../../resources/emoji/11.gif'));
emoji.set(12,require('../../resources/emoji/12.gif'));
emoji.set(13,require('../../resources/emoji/13.gif'));
emoji.set(14,require('../../resources/emoji/14.gif'));
emoji.set(15,require('../../resources/emoji/15.gif'));
emoji.set(16,require('../../resources/emoji/16.gif'));
emoji.set(18,require('../../resources/emoji/18.gif'));
emoji.set(19,require('../../resources/emoji/19.gif'));
emoji.set(20,require('../../resources/emoji/20.gif'));
emoji.set(21,require('../../resources/emoji/21.gif'));
emoji.set(25,require('../../resources/emoji/25.gif'));
emoji.set(26,require('../../resources/emoji/26.gif'));
emoji.set(27,require('../../resources/emoji/27.gif'));
emoji.set(29,require('../../resources/emoji/29.gif'));
emoji.set(32,require('../../resources/emoji/32.gif'));
emoji.set(34,require('../../resources/emoji/34.gif'));
emoji.set(36,require('../../resources/emoji/36.gif'));
emoji.set(39,require('../../resources/emoji/39.gif'));
emoji.set(40,require('../../resources/emoji/40.gif'));
emoji.set(41,require('../../resources/emoji/41.gif'));
emoji.set(42,require('../../resources/emoji/42.gif'));
emoji.set(44,require('../../resources/emoji/44.gif'));
emoji.set(47,require('../../resources/emoji/47.gif'));
emoji.set(49,require('../../resources/emoji/49.gif'));
emoji.set(50,require('../../resources/emoji/50.gif'));
emoji.set(51,require('../../resources/emoji/51.gif'));
emoji.set(53,require('../../resources/emoji/53.gif'));
emoji.set(54,require('../../resources/emoji/54.gif'));


export default emoji;
